# Generated by Django 5.2.1 on 2025-06-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='site_officiel',
            field=models.URLField(blank=True),
        ),
    ]
