# Generated by Django 5.2.1 on 2025-06-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_distribution_site_officiel'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='categorie',
            field=models.CharField(choices=[('Debian', 'Debian-based'), ('Arch', 'Arch-based'), ('RedHat', 'RedHat-based')], default=1, max_length=100),
        ),
    ]
