# Generated by Django 5.2.1 on 2025-06-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_distribution_categorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribution',
            options={'verbose_name': 'Distribution Linux', 'verbose_name_plural': 'Distributions Linux'},
        ),
        migrations.AlterModelOptions(
            name='tutoriel',
            options={'verbose_name': 'Tutoriel', 'verbose_name_plural': 'Tutoriels'},
        ),
        migrations.RenameField(
            model_name='distribution',
            old_name='descriptiion',
            new_name='description',
        ),
        migrations.AddField(
            model_name='distribution',
            name='checksum_sha256',
            field=models.CharField(blank=True, max_length=64, verbose_name='SHA256 Checksum'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='environnement_bureau',
            field=models.CharField(choices=[('gnome', 'GNOME'), ('kde', 'KDE Plasma'), ('xfce', 'Xfce'), ('cinnamon', 'Cinnamon'), ('mate', 'MATE'), ('lxqt', 'LXQt'), ('autre', 'Autre / Minimaliste')], default='gnome', max_length=50, verbose_name='Environnement de bureau par défaut'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='lien_telechargement_direct',
            field=models.URLField(blank=True, verbose_name='Lien de téléchargement direct (.iso)'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='lien_telechargement_torrent',
            field=models.URLField(blank=True, verbose_name='Lien Torrent / Magnet'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='modele_publication',
            field=models.CharField(choices=[('stable', 'Stable (Mises à jour par version)'), ('rolling', 'Rolling Release (Mises à jour continues)')], default='stable', max_length=20, verbose_name='Modèle de publication'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='niveau_experience',
            field=models.CharField(choices=[('débutant', 'Débutant'), ('intermédiaire', 'Intermédiaire'), ('expert', 'Expert')], default='débutant', max_length=20, verbose_name="Niveau d'expérience recommandé"),
        ),
        migrations.AddField(
            model_name='distribution',
            name='ressources_requises',
            field=models.CharField(choices=[('faibles', 'Faibles (vieux PC)'), ('moyennes', 'Moyennes'), ('elevees', 'Élevées (hautes performances)')], default='moyennes', max_length=20, verbose_name='Ressources matérielles requises'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='usage_principal',
            field=models.CharField(choices=[('bureau', 'Bureau (usage quotidien)'), ('serveur', 'Serveur'), ('gaming', 'Gaming'), ('sécurité', 'Sécurité / Pentesting'), ('dev', 'Développement'), ('ancien_pc', 'Ancien PC / Faibles ressources'), ('embarque', 'Système Embarqué'), ('multimedia', 'Multimédia')], default='bureau', max_length=50, verbose_name='Usage principal'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='categorie',
            field=models.CharField(choices=[('Debian', 'Debian-based'), ('Ubuntu', 'Ubuntu-based'), ('Arch', 'Arch-based'), ('RedHat', 'Red Hat / Fedora / CentOS-based'), ('Suse', 'OpenSUSE / SUSE-based'), ('Autre', 'Indépendante / Autre')], default='Autre', max_length=100),
        ),
    ]
