# Generated by Django 5.2.1 on 2025-06-11 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_distribution_options_alter_tutoriel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribution',
            options={'ordering': ['nom'], 'verbose_name': 'Distribution Linux', 'verbose_name_plural': 'Distributions Linux'},
        ),
        migrations.AlterModelOptions(
            name='tutoriel',
            options={'ordering': ['-date_publication'], 'verbose_name': 'Tutoriel', 'verbose_name_plural': 'Tutoriels'},
        ),
        migrations.RenameField(
            model_name='tutoriel',
            old_name='Distribution',
            new_name='distribution',
        ),
        migrations.AlterField(
            model_name='tutoriel',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
